contrib/git-abc-backport-diff: Fix and improve
It turns out that git-range-diff was a bad choice for doing the
diff parsing since it's output is not stable. Switch to 'diff -u'
like the original git-backport-diff uses. Also, integrate with
git better by using git-sh-setup and implement git-backport-diff's
diff viewing feature (where we can use git-range-diff). Finally,
if the user has an ABC_NAMESPACE set in their environment, then
use that instead of a temporary one with a set-upstream-range.

diff --git a/contrib/git-abc-backport-diff b/contrib/git-abc-backport-diff
--- a/contrib/git-abc-backport-diff
+++ b/contrib/git-abc-backport-diff
@@ -1,19 +1,19 @@
 #!/bin/bash
 #SPDX-License-Identifier: MIT
 
-git rev-parse --git-dir >/dev/null
-
 cmd="git-abc-backport-diff"
 
-help()
-{
-	cat <<EOF
-$cmd [OPTIONS]
-OPTIONS:
+SUBDIRECTORY_OK=true
+USAGE="[-r <range>] [-u <upstream>] [-p] [-s <level>] [-S]"
+LONG_USAGE="OPTIONS:
     -r git range
        optional; default is '\${ABC_DOWNSTREAM}..'
     -u upstream git tag / branch / id
        optional; default is '\$ABC_UPSTREAM'
+    -p do not pause when viewing diffs
+    -s sensitivity level of diff compares
+       0:  only show functional code differences
+       1:  show (0) + contextual differences
     -S summary only (no diff viewing)
     -h help
 
@@ -21,10 +21,13 @@ OPTIONS:
       git config backport-diff.upstream
       git config backport-diff.range
       git config backport-diff.summary
+"
+. "$(git --exec-path)/git-sh-setup"
+set_reflog_action abc-backport-diff
 
-(Currently summary (-S) is the only supported feature and must be selected.)
-EOF
-}
+if ! command -v git-abc >/dev/null; then
+	die "$cmd requires git-abc"
+fi
 
 do_summary()
 {
@@ -73,14 +76,32 @@ do_summary()
 	done
 }
 
-if git range-diff |& grep -q 'not a git command'; then
-	echo "$cmd requires git-range-diff"
-	exit 1
-fi
-if ! command -v git-abc >/dev/null; then
-	echo "$cmd requires git-abc"
-	exit 1
-fi
+do_diff()
+{
+	local level=$1 c
+
+	if git range-diff |& grep -q 'not a git command'; then
+		die "$cmd -s requires git-range-diff"
+	fi
+
+	for c in ${!upstream[*]}; do
+		[[ ${diff_functional[$c]} ]] || diff_functional[$c]=0
+		[[ ${diff_contextual[$c]} ]] || diff_contextual[$c]=0
+
+		if (( ${diff_functional[$c]} == 0 && ${diff_contextual[$c]} == 0 )); then
+			continue
+		elif [[ $level == '0' ]] && (( ${diff_functional[$c]} == 0 )); then
+			continue
+		fi
+
+		if [[ $no_pause ]]; then
+			git range-diff ${c}^..${c} ${upstream[$c]}^..${upstream[$c]} | cat
+		else
+			git range-diff ${c}^..${c} ${upstream[$c]}^..${upstream[$c]}
+			echo; read -p "press enter to continue" cont
+		fi
+	done
+}
 
 range=$(git config backport-diff.range || true)
 upstream=$(git config backport-diff.upstream || true)
@@ -89,14 +110,14 @@ while [[ $1 ]]; do
 	case "$1" in
 	-r)	range=$2; shift 2;;
 	-u)	upstream=$2; shift 2;;
+	-p)	no_pause=1; shift 1;;
+	-s)	show_diff=$2; shift 2;;
 	-S)	summary=y; shift;;
-	-h)	help; exit;;
-	*)	shift;;
+	*)	"$0" -h;;
 	esac
 done
-if [[ $summary != y ]]; then
-	echo "Summary (-S) must be selected."
-	exit 1
+if [[ -z $show_diff && -z $summary ]]; then
+	summary=y
 fi
 if [[ ${range:(-2)} == '^!' ]]; then
 	base=${range:0:(-1)}
@@ -107,22 +128,23 @@ fi
 if [[ $base ]] && [[ ! $upstream ]]; then
 	upstream=$(git abc get-config | awk -F= '/^ABC_UPSTREAM=/ {print$2}')
 	if [[ ! $upstream ]]; then
-		echo "No upstream known for base $base" >&2
-		exit 1
+		die "No upstream known for base $base" >&2
 	fi
 fi
 
-git abc get-config $upstream $base -- >/dev/null || exit $?
+[[ -z $ABC_NAMESPACE ]] && tmp_namespace=y
+git abc get-config $upstream $base -- >/dev/null || die "Failed to get git-abc config"
 eval export $(git abc get-config $upstream $base --)
-export ABC_NAMESPACE="git-abc-$(mktemp -u XXXXXXXX)"
-export ABC_HUNT_CHERRIES=false
+if [[ $tmp_namespace ]]; then
+	export ABC_NAMESPACE="git-abc-$(mktemp -u XXXXXXXX)"
+	export ABC_HUNT_CHERRIES=false
+fi
 
 if [[ ! $range ]]; then
 	base=$ABC_DOWNSTREAM
 	range="${base}.."
 elif [[ ! $range =~ '..' ]]; then
-	echo "fatal: no .. in range: '$range'"
-	exit 1
+	die "fatal: no .. in range: '$range'"
 fi
 if [[ ! $upstream ]]; then
 	upstream=$ABC_UPSTREAM
@@ -132,19 +154,29 @@ fi
 #	 otherwise it's just not practical to use it. A workaround is to only run this in a
 #	 git repo with the desired upstream available, as set-upstream-range will still complain
 #	 when the upstream commits aren't valid.
+#
+# (Using commitGraph solves the performance problem, but git abc set-upstream-range has a bug
+#  that needs fixing too.)
+#
 #upstream_range="$(git merge-base $base $upstream)..${upstream}"
 
-trap 'git abc reset -f; exit' EXIT HUP INT TERM
-git abc set-upstream-range $range $upstream_range 2>/dev/null
+if [[ $tmp_namespace ]]; then
+	trap 'git abc reset -f; exit' EXIT HUP INT TERM
+	git abc set-upstream-range $range $upstream_range 2>/dev/null
+fi
 
-declare -A diff_functional diff_contextual
+declare -A diff_functional diff_contextual upstream
 for c in $(git log --reverse --pretty='%h:%N' --notes=$ABC_NAMESPACE --grep ABC_UPSTREAM $range); do
 	u=${c/*=/} c=${c/:*/}
-	diff_no_msg=$(git range-diff $u^..$u $c^..$c | awk '{if (/^    [ +-] diff / || p) {print$0; p=1}}')
-	diff_functional[$c]=$(grep -c -e '^    ++' -e '^    --' -e '^    +-' -e '^    -+' <<<"$diff_no_msg")
-	diff_contextual[$c]=$(grep -c -e '^    + ' -e '^    - ' -e '^     +' -e '^     -' <<<"$diff_no_msg")
+	diff_lines=$(diff -u <(git diff $u^\!) <(git diff $c^\!) | awk '/^\+\+|^--|^\+-|^-\+|^\+ |^- |^ \+|^ -/ && !/^[\+\- ]?\+\+\+ |^[\+\- ]?--- / {print$0}')
+	diff_functional[$c]=$(grep -c -e '^++' -e '^--' -e '^+-' -e '^-+' <<<"$diff_lines")
+	diff_contextual[$c]=$(grep -c -e '^+ ' -e '^- ' -e '^ +' -e '^ -' <<<"$diff_lines")
+	upstream[$c]=$u
 done
 
 if [[ $summary == y ]]; then
 	do_summary
+fi
+if [[ $show_diff ]]; then
+	do_diff $show_diff
 fi
