contrib/git-abc-backport-diff: Fix and improve (round 2)
Finish porting all the functionality from the original git-backport-diff
that we intend to take. Also apply a few fixes and cleanups and do
everything that shellcheck tells us to do.

diff --git a/contrib/git-abc-backport-diff b/contrib/git-abc-backport-diff
--- a/contrib/git-abc-backport-diff
+++ b/contrib/git-abc-backport-diff
@@ -3,8 +3,10 @@
 
 cmd="git-abc-backport-diff"
 
+# shellcheck disable=SC2034
+{
 SUBDIRECTORY_OK=true
-USAGE="[-r <range>] [-u <upstream>] [-p] [-s <level>] [-S]"
+USAGE="[-r <range>] [-u <upstream>] [-p] [-s <level>] [-S] [-n] [-- options...]"
 LONG_USAGE="OPTIONS:
     -r git range
        optional; default is '\${ABC_DOWNSTREAM}..'
@@ -14,14 +16,23 @@ LONG_USAGE="OPTIONS:
     -s sensitivity level of diff compares
        0:  only show functional code differences
        1:  show (0) + contextual differences
+       2:  show all patches, regardless of any differences
     -S summary only (no diff viewing)
+    -n do not show summary
     -h help
 
     You can set each of the default options using git-config:
       git config backport-diff.upstream
       git config backport-diff.range
+      git config backport-diff.pause
       git config backport-diff.summary
+      git config backport-diff.sensitivity
+
+    Additionally, follow the backport-diff options with '-- options...'
+    to pass 'options...' to git-range-diff
 "
+}
+# shellcheck source=/dev/null
 . "$(git --exec-path)/git-sh-setup"
 set_reflog_action abc-backport-diff
 
@@ -29,9 +40,23 @@ if ! command -v git-abc >/dev/null; then
 	die "$cmd requires git-abc"
 fi
 
+check_streams()
+{
+	local upstream=$1 downstream=$2
+	ABC_UPSTREAM=$upstream ABC_DOWNSTREAM=$downstream git abc get-config -- >&/dev/null ||
+		die "Please check that range and upstream are specified correctly"
+}
+
+abc_get_config()
+{
+	local upstream=$1 downstream=$2
+	ABC_UPSTREAM=$upstream ABC_DOWNSTREAM=$downstream git abc get-config --
+}
+
 do_summary()
 {
-	declare -i total count
+	declare -i idx=1
+	local c subject field1 flags
 
 	echo 'Key:'
 	echo '[----] : patches are identical'
@@ -40,16 +65,10 @@ do_summary()
 	echo 'The flags [FC] indicate (F)unctional and (C)ontextual differences, respectively'
 	echo
 
-	total=$(git rev-list --count $range)
-	count=1
-
-	git log --reverse --pretty='%h %s' $range | while read -r c subject; do
-		[[ ${diff_functional[$c]} ]] || diff_functional[$c]=0
-		[[ ${diff_contextual[$c]} ]] || diff_contextual[$c]=0
-
+	git log --reverse --pretty='%h %s' "$range" | while read -r c subject; do
 		if [[ ${diff_functional[$c]} != 0 ]]; then
-			field1=$(printf "%04d" ${diff_functional[$c]})
-		elif git notes --ref $ABC_NAMESPACE show $c 2>/dev/null | grep -q ABC_ONLY_DOWNSTREAM; then
+			field1=$(printf "%04d" "${diff_functional[$c]}")
+		elif git notes --ref "$ABC_NAMESPACE" show "$c" 2>/dev/null | grep -q ABC_ONLY_DOWNSTREAM; then
 			field1='down'
 		else
 			field1='----'
@@ -71,84 +90,99 @@ do_summary()
 			flags=" [$flags]"
 		fi
 
-		printf "%03d/$total:[$field1]$flags '%s'\n" "$count" "$subject"
-		((++count))
+		printf "%03d/$total:[$field1]$flags '%s'\n" "$idx" "$subject"
+		((++idx))
 	done
 }
 
 do_diff()
 {
-	local level=$1 c
+	declare -i idx=1
+	local c u patch
 
 	if git range-diff |& grep -q 'not a git command'; then
 		die "$cmd -s requires git-range-diff"
 	fi
 
-	for c in ${!upstream[*]}; do
-		[[ ${diff_functional[$c]} ]] || diff_functional[$c]=0
-		[[ ${diff_contextual[$c]} ]] || diff_contextual[$c]=0
+	for c in $(git log --reverse --pretty=%h "$range"); do
+		patch=$(printf "%03d/$total" $idx)
+		((++idx))
 
-		if (( ${diff_functional[$c]} == 0 && ${diff_contextual[$c]} == 0 )); then
+		u=${upstream_links[$c]}
+
+		if [[ ! $u ]]; then
 			continue
-		elif [[ $level == '0' ]] && (( ${diff_functional[$c]} == 0 )); then
+		elif (( sensitivity < 2 && ${diff_functional[$c]} == 0 && ${diff_contextual[$c]} == 0 )); then
+			continue
+		elif (( sensitivity < 1 && ${diff_functional[$c]} == 0 )); then
 			continue
 		fi
 
-		if [[ $no_pause ]]; then
-			git range-diff ${c}^..${c} ${upstream[$c]}^..${upstream[$c]} | cat
+		if [[ $pause != false ]]; then
+			echo; read -r -p "Press [Enter] to view $patch: $(git log -n1 --pretty=%s "$c")"
+			git range-diff "${options[@]}" "${u}"^.."${u}" "${c}"^.."${c}"
 		else
-			git range-diff ${c}^..${c} ${upstream[$c]}^..${upstream[$c]}
-			echo; read -p "press enter to continue" cont
+			echo; echo -n "$patch: "
+			git range-diff "${options[@]}" "${u}"^.."${u}" "${c}"^.."${c}" | cat
 		fi
 	done
 }
 
 range=$(git config backport-diff.range || true)
 upstream=$(git config backport-diff.upstream || true)
-summary=$(git config backport-diff.summary || true)
-while [[ $1 ]]; do
-	case "$1" in
-	-r)	range=$2; shift 2;;
-	-u)	upstream=$2; shift 2;;
-	-p)	no_pause=1; shift 1;;
-	-s)	show_diff=$2; shift 2;;
-	-S)	summary=y; shift;;
-	*)	"$0" -h;;
+summary=$(git config --type bool backport-diff.summary || echo false)
+pause=$(git config --type bool backport-diff.pause || echo true)
+sensitivity=$(git config --type int backport-diff.sensitivity || echo 0)
+
+while getopts ":hr:u:ps:Sn" opt; do
+	case "$opt" in
+	r)	range=$OPTARG;;
+	u)	upstream=$OPTARG;;
+	p)	pause=false;;
+	s)	sensitivity=$OPTARG
+		if [[ ! "$sensitivity" =~ ^[0-2]$ ]]; then
+			echo "Invalid argument for -s" >&2
+			usage
+		fi;;
+	S)	summary=true;;
+	n)	no_summary=true;;
+	h)	"$0" -h;;
+	\?)	echo "Unknown option: -$OPTARG" >&2; usage;;
 	esac
 done
-if [[ -z $show_diff && -z $summary ]]; then
-	summary=y
-fi
+shift $((OPTIND - 1))
+read -r -a options <<<"$@"
+
 if [[ ${range:(-2)} == '^!' ]]; then
 	base=${range:0:(-1)}
 	range="${base}..${range:0:(-2)}"
+elif [[ $range && ! $range =~ \.\. ]]; then
+	die "fatal: no .. in range: '$range'"
 elif [[ $range ]]; then
 	base=${range/..*/}
 fi
-if [[ $base ]] && [[ ! $upstream ]]; then
-	upstream=$(git abc get-config | awk -F= '/^ABC_UPSTREAM=/ {print$2}')
-	if [[ ! $upstream ]]; then
-		die "No upstream known for base $base" >&2
-	fi
-fi
 
+check_streams "$upstream" "$base"
+
+: "${ABC_NAMESPACE:=$(git config --get abc.namespace)}"
 [[ -z $ABC_NAMESPACE ]] && tmp_namespace=y
-git abc get-config $upstream $base -- >/dev/null || die "Failed to get git-abc config"
-eval export $(git abc get-config $upstream $base --)
-if [[ $tmp_namespace ]]; then
-	export ABC_NAMESPACE="git-abc-$(mktemp -u XXXXXXXX)"
-	export ABC_HUNT_CHERRIES=false
-fi
+
+# shellcheck source=/dev/null
+. <(abc_get_config "$upstream" "$base")
+export ABC_NAMESPACE
 
 if [[ ! $range ]]; then
 	base=$ABC_DOWNSTREAM
 	range="${base}.."
-elif [[ ! $range =~ '..' ]]; then
-	die "fatal: no .. in range: '$range'"
 fi
 if [[ ! $upstream ]]; then
 	upstream=$ABC_UPSTREAM
 fi
+
+if [[ $tmp_namespace ]]; then
+	ABC_NAMESPACE="git-abc-$(mktemp -u XXXXXXXX)"
+	export ABC_NAMESPACE
+	trap 'git abc reset -f; exit' EXIT HUP INT TERM
 
 # FIXME: Need to improve the performance set-upstream-range with a specified upstream range,
 #	 otherwise it's just not practical to use it. A workaround is to only run this in a
@@ -158,25 +192,37 @@ fi
 # (Using commitGraph solves the performance problem, but git abc set-upstream-range has a bug
 #  that needs fixing too.)
 #
-#upstream_range="$(git merge-base $base $upstream)..${upstream}"
+#	upstream_range="$(git merge-base "$base" "$upstream")..${upstream}"
 
-if [[ $tmp_namespace ]]; then
-	trap 'git abc reset -f; exit' EXIT HUP INT TERM
-	git abc set-upstream-range $range $upstream_range 2>/dev/null
+	git -c abc.hunt-cherries=off abc set-upstream-range "$range" "$upstream_range" 2>/dev/null
 fi
 
-declare -A diff_functional diff_contextual upstream
-for c in $(git log --reverse --pretty='%h:%N' --notes=$ABC_NAMESPACE --grep ABC_UPSTREAM $range); do
-	u=${c/*=/} c=${c/:*/}
-	diff_lines=$(diff -u <(git diff $u^\!) <(git diff $c^\!) | awk '/^\+\+|^--|^\+-|^-\+|^\+ |^- |^ \+|^ -/ && !/^[\+\- ]?\+\+\+ |^[\+\- ]?--- / {print$0}')
+declare -A diff_functional diff_contextual upstream_links
+declare -i total
+
+total=$(git rev-list --count "$range")
+
+for p in $(git log --pretty='%h:%N' --notes="$ABC_NAMESPACE" "$range"); do
+	u=${p/*=/} c=${p/:*/}
+	diff_functional[$c]=0
+	diff_contextual[$c]=0
+
+	if [[ $p =~ ABC_ONLY_DOWNSTREAM ]]; then
+		continue
+	elif [[ $p =~ ABC_CHERRYPICK ]]; then
+		upstream_links[$c]=$u
+		continue
+	elif [[ ! $p =~ ABC_UPSTREAM ]]; then
+		echo "Must set upstream links on $range of git-abc namespace $ABC_NAMESPACE first" >&2
+		echo "Try git -c abc.namespace=$ABC_NAMESPACE abc set-upstream-range $range $upstream_range" >&2
+		exit 1
+	fi
+
+	diff_lines=$(diff -u <(git diff "$u"^\!) <(git diff "$c"^\!) | awk '/^\+\+|^--|^\+-|^-\+|^\+ |^- |^ \+|^ -/ && !/^[\+\- ]?\+\+\+ |^[\+\- ]?--- / {print$0}')
 	diff_functional[$c]=$(grep -c -e '^++' -e '^--' -e '^+-' -e '^-+' <<<"$diff_lines")
 	diff_contextual[$c]=$(grep -c -e '^+ ' -e '^- ' -e '^ +' -e '^ -' <<<"$diff_lines")
-	upstream[$c]=$u
+	upstream_links[$c]=$u
 done
 
-if [[ $summary == y ]]; then
-	do_summary
-fi
-if [[ $show_diff ]]; then
-	do_diff $show_diff
-fi
+[[ $no_summary != true ]] && do_summary
+[[ $summary != true ]] && do_diff
