Cleanup revision determination and improve its error paths

diff --git a/git-abc b/git-abc
--- a/git-abc
+++ b/git-abc
@@ -388,62 +388,70 @@ abc_get_downstream_revision()
 {
 	if [ "$ABC_DOWNSTREAM" = "" ]; then
 		ABC_DOWNSTREAM=$(git config --get abc.downstream)
-		if [ "$ABC_DOWNSTREAM" ] && ! git rev-parse --verify -q "$ABC_DOWNSTREAM" >/dev/null; then
-			die_error "abc.downstream='$ABC_DOWNSTREAM' is not a valid downstream revision"
-		elif [ "$ABC_DOWNSTREAM" = "" ]; then
-			ABC_DOWNSTREAM=HEAD
-		fi
+	fi
+
+	if [ "$ABC_DOWNSTREAM" = "" ]; then
+		ABC_DOWNSTREAM=HEAD
+	elif ! git rev-parse --verify -q "$ABC_DOWNSTREAM" >/dev/null; then
+		die_error "'$ABC_DOWNSTREAM' is not a valid downstream revision"
 	fi
 }
 
 abc_get_upstream_revision()
 {
-	local branches=()
-	local downstream_branch
+	local branch=()
 
 	if [ "$ABC_UPSTREAM" = "" ]; then
 		ABC_UPSTREAM=$(git config --get abc.upstream)
-		if [ "$ABC_UPSTREAM" ] && ! git rev-parse --verify -q "$ABC_UPSTREAM" >/dev/null; then
-			die_error "abc.upstream='$ABC_UPSTREAM' is not a valid upstream revision"
-		fi
 	fi
 
 	if [ "$ABC_UPSTREAM" = "" ]; then
 		abc_get_downstream_revision
-		branches=($(git branch --contains "$ABC_DOWNSTREAM" | sed 's/^\* //'))
-		if [ "${branches[1]}" ]; then
+		branch=($(git branch --contains "$ABC_DOWNSTREAM" | sed 's/^\* //'))
+		if [ "${branch[1]}" ]; then
 			# We don't know which branch to use in our guess, so we can't guess.
 			die "Can't guess abc.upstream from abc.downstream $ABC_DOWNSTREAM. Please specify."
 		fi
-		downstream_branch="${branches[0]}"
-		ABC_UPSTREAM="$downstream_branch@{upstream}"
-		if ! git rev-parse "$ABC_UPSTREAM" >&/dev/null; then
-			die "No upstream associated with '$ABC_DOWNSTREAM's branch '$downstream_branch'."
-		fi
+		ABC_UPSTREAM="${branch[0]}@{upstream}"
+	fi
+
+	if ! git rev-parse --verify -q "$ABC_UPSTREAM" >/dev/null; then
+		die_error "'$ABC_UPSTREAM' is not a valid upstream revision"
+	fi
+}
+
+abc_get_revisions()
+{
+	abc_get_upstream_revision
+	abc_get_downstream_revision
+
+	if [[ "$(git rev-parse $ABC_UPSTREAM)" == "$(git rev-parse $ABC_DOWNSTREAM)" ]]; then
+		die "upstream and downstream cannot be the same reference"
 	fi
 }
 
 abc_get_limits()
 {
-	if [ "$1" ] && [ "$1" != '--' ]; then
-		if git rev-parse --verify -q "$1" >/dev/null; then
-			ABC_UPSTREAM=$1
+	if [[ -n $1 ]] && [[ $1 != -- ]] && git rev-parse --verify -q "$1" >/dev/null; then
+		ABC_UPSTREAM=$1
+		shift
+		if [[ -n $1 ]] && [[ $1 != -- ]] && git rev-parse --verify -q "$1" >/dev/null; then
+			ABC_DOWNSTREAM=$1
 			shift
-			if git rev-parse --verify -q "$1" >/dev/null; then
-				ABC_DOWNSTREAM=$1
-				shift
-			fi
+		elif [[ $2 == -- ]]; then
+			die_error "'$1' is not a valid downstream revision"
 		fi
+	elif [[ $2 == -- ]] || [[ $3 == -- ]]; then
+		die_error "'$1' is not a valid upstream revision"
 	fi
-	if [ "$1" = '--' ]; then
+	if [[ $1 == -- ]]; then
 		shift
 	fi
-	if [ "$1" ]; then
+	if [[ -n $1 ]]; then
 		ABC_PATHS="$*"
 	fi
 
-	abc_get_downstream_revision
-	abc_get_upstream_revision
+	abc_get_revisions
 }
 
 abc_should_highlight()
